Tko may 2024
qentinelqi/qweb pull request #148
Opened 2024-04-30 07:09 UTC by tkoukkari

**WIP**
_New commits may still be added, but existing commits can be reviewed/commented already._

- fix for #145
- refactoring unit tests, removing deprecated method names
- refactored the way we get version number on OpenBrowser (pkg_resources is deprecated)
- fix: VerifyTable to not break on "special characters" like "[", "]", "*" or "?"
- feat: add support for treating color differences as meaningful in *Icon keywords. Also expose "tolerance" argument.
- feat: browser and driver management support (Selenium Manager) for edge and firefox
- fix: added possibility to strip newlines to GetInputValue (#144)
- fix: UploadFile to find inputs of type file when searching with xpath locator

2024-05-02 08:04 UTC, turunenm requested changes
Requested some naming changes but otherwise looks good

2024-05-02 08:04 UTC, turunenm commented on QWeb/internal/actions.py
> +        not partial_match and text_to_compare == expected
Isn't the check for `not partial_match` redundant

This should be equivalent check
`if text_to_compare == expected or (partial_match and expected in text_to_compare)`

2024-05-02 08:04 UTC, turunenm commented on QWeb/internal/icon.py
> +        grayscale: bool = False,
Since the check used to be grayscale only I think this should default to `True`

2024-05-02 08:04 UTC, turunenm commented on QWeb/internal/icon.py
> +        image_gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY) if grayscale else image
`image_gray` is misleading variable name as it can now be in color

Rename the var to something like `image_haystack`

2024-05-02 08:04 UTC, turunenm commented on QWeb/internal/util.py
> +def get_substring(text: str, strip_newlines: bool = True, **kwargs) -> Union[int, float, str]:
The new flag removes all newlines instead of stripping them and should be renamed to `remove_newlines`
Stripping in Python means removing provided characters from the start/end of the string.

Semantic nitpicking but this could cause confusion at some point.

2024-05-02 08:04 UTC, turunenm commented on QWeb/keywords/input_.py
> +    strip_newlines: bool = True,
The new flag removes all newlines instead of stripping them and should be renamed to `remove_newlines`
Stripping in Python means removing provided characters from the start/end of the string.

Semantic nitpicking but this could cause confusion at some point.

2024-05-02 08:04 UTC, turunenm commented on QWeb/keywords/input_.py
> +        Strip new lines (\n)from string, especially from multirow text areas. Default = True
`remove_newlines`

2024-05-02 08:04 UTC, turunenm commented on QWeb/keywords/input_.py
> +    return util.get_substring(val, strip_newlines=strip_newlines, **kwargs)
`remove_newlines`

2024-05-02 08:04 UTC, turunenm commented on QWeb/internal/util.py
> +    if strip_newlines:
`remove_newlines`

2024-05-02 08:04 UTC, turunenm commented on ruff.toml
> +# docstring-code-format = false
Does this affect generated kw docs in any way after running `ruff format`?

2024-05-02 08:21 UTC, tkoukkari commented on QWeb/internal/actions.py
> +        not partial_match and text_to_compare == expected
Yes, that's true. Will change with new commit.

2024-05-02 08:25 UTC, tkoukkari commented on QWeb/internal/icon.py
> +        grayscale: bool = False,
will update with new commit

2024-05-02 08:26 UTC, tkoukkari commented on QWeb/internal/icon.py
> +        image_gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY) if grayscale else image
will rename in new commit

2024-05-02 08:27 UTC, tkoukkari commented on QWeb/internal/util.py
> +def get_substring(text: str, strip_newlines: bool = True, **kwargs) -> Union[int, float, str]:
ok, didn't think of it that way but valid point. Will update with new commit.

2024-05-02 08:29 UTC, tkoukkari commented on QWeb/keywords/input_.py
> +    strip_newlines: bool = True,
ok, didn't think of it that way but valid point. Will update with new commit.

2024-05-02 08:34 UTC, tkoukkari commented on QWeb/keywords/input_.py
> +        Strip new lines (\n)from string, especially from multirow text areas. Default = True
will update with new commit

2024-05-02 08:34 UTC, tkoukkari commented on QWeb/internal/util.py
> +    if strip_newlines:
will update with new commit

2024-05-02 08:35 UTC, tkoukkari commented on ruff.toml
> +# docstring-code-format = false
not sure, but I don't think so. At least kw docs look normal

2024-05-02 10:15 UTC, tkoukkari commented
> Requested some naming changes but otherwise looks good

All of these should be now included with the latest commit

2024-05-02 10:51 UTC, turunenm approved these changes
lgtm

2024-05-06 12:25 UTC, tkoukkari commented
**Note:** MacOS/Safari tests are failing due to restriction of running local html files. This will be fixed in another PR.

2024-05-06 12:27 UTC, merged